### ISSUE TITLE
BAD_ACCESS onUnpublishNotification

### ISSUE THREAD

**Issue by stijnvanderlaan** [infrared5/react-native-red5pro#20]
![screen shot 2018-04-13 at 16 29 13](https://user-images.githubusercontent.com/20322260/38740681-755d1e94-3f38-11e8-9b90-7030160bc84b.png)

![screen shot 2018-04-13 at 16 35 43](https://user-images.githubusercontent.com/20322260/38740815-c6cb340a-3f38-11e8-93d1-e45e41e34239.png)

(should probably be onUnsubscribeNotification?)

**Comment by bustardcelly** [comment]
@stijnvanderlaan Nice catch regarding the `onUnsubscribeNotification` issue.

The additional issue of `BAD_ACCESS` I cannot reproduce. Can you provide specific steps that lead up to this exception?

**Comment by stijnvanderlaan** [comment]
Strange, I also can't reproduce this anymore.
