### ISSUE TITLE
Bug: Adding R5Pro SDK breaks React header files

### ISSUE THREAD

**Issue by iamclaytonray** [infrared5/react-native-red5pro#9]
I don't have a repro just yet. I'll try to get that over today in a public repo. Essentially, XCode & Android Studio both fail to compile when the Red5Pro SDK is added. This addition causes React's headers to not install. After completely resetting/removing R5Pro from my app, it compiled perfectly.

**Comment by iamclaytonray** [comment]
@bustardcelly - What's the status on this issue?

**Comment by bustardcelly** [comment]
Hello @iamclaytonray sorry for the delayed response.

Have you looked at the project structure in the `example` directory? The SDK is able to reside as a dependency without issue.

Are you able to simply link this component using `npm install` and `react-native link`? Or do you have to manually add the `react-native-red5pro` component to the projects?

**Comment by iamclaytonray** [comment]
I have to do everything manually, however, neither method works

**Comment by bustardcelly** [comment]
Hrm...

Have you been able to successfully build and deploy with the `example` projects?
